spring:
  application:
    name: ApiGateway



  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
                    - POST
                    - GET
                    - OPTIONS
                    - PUT
                    - DELETE

server:
      port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka


