spring:
  application:
    name: ApiGateway



  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

#  cloud:
#    gateway:
#      routes:
#        - id: User
#          uri: http://localhost:4004
#          predicates:
#            - Path=/api/v1/users/**
#          filters:
#            - AuthenticationFilter
#
#        - id: AuthService
#          uri: http://localhost:4003
#          predicates:
#            - Path=/api/v1/auth/**
#          filters:
#            - AuthenticationFilter

server:
  port: 4001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4000/eureka
